logging:
  level:
    com.jywoo.payment: DEBUG

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    data: classpath:sql/import.sql
    url: 'jdbc:h2:mem:da;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE'
    driver-class-name: org.h2.Driver
    username: payment_user
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true